concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800
[[runners]]
  name = "machine-on-digital-ocean"
  url = "https://git.fa.edu.vn/"
  id = 350
  token = "glrt-RgLnSYFnhk77nQxeEjT9"
  token_obtained_at = 2025-06-08T18:53:49Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:24.0.5"
    privileged = true
    disable_cache = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache", "/certs/client"]
    shm_size = 0
    network_mtu = 0