packages:
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - cypress
  - esbuild
  - nx
  - sharp

packageExtensions:
  vite:
    dependencies:
      vite: "^6.0.0"
